# https://www.virtualbox.org/wiki/Linux_Downloads
---
- name: Setup VirtualBox
  hosts: all
  become: true
  vars:
    vbox_version: 7.2
    vbox_package_name: >-
      {%- if ansible_facts['os_family'] == "Debian" -%}
        virtualbox-{{ vbox_version }}
      {%- elif ansible_facts['os_family'] == "RedHat" -%}
        VirtualBox-{{ vbox_version }}
      {%- endif -%}

  tasks:
    - name: Add repository (Debian)
      ansible.builtin.include_tasks:
        file: tasks/add_debian_repo.yml
      vars:
        debrepo_gpg_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        debrepo_gpg_key_path: /usr/share/keyrings/oracle-virtualbox-2016.gpg
        debrepo_string: >-
          deb [arch={{ debrepo_dpkg_arch.stdout }} signed-by={{ debrepo_gpg_key_path }}]
          https://download.virtualbox.org/virtualbox/debian {{ debrepo_distro_codename.stdout }} contrib
      when: ansible_facts['os_family'] == "Debian"

    - name: Add repository (RedHat)
      ansible.builtin.get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/{{ vbox_redhat_repo }}/virtualbox.repo
        dest: /etc/yum.repos.d/virtualbox.repo
        mode: "0644"
      vars:
        vbox_redhat_repo: "{% if ansible_facts['distribution'] == \"Fedora\" %}fedora{% else %}el{% endif %}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install VirtualBox
      ansible.builtin.package:
        name: "{{ vbox_package_name }}"
        state: present

    - name: Validate install
      ansible.builtin.command:
        cmd: vboxmanage --version
      changed_when: false
