# https://developer.hashicorp.com/vagrant/install
---
- name: Setup Vagrant
  hosts: all
  become: true
  tasks:
    - name: Add repository (Debian)
      ansible.builtin.include_tasks:
        file: tasks/add_debian_repo.yml
      vars:
        debrepo_gpg_key_url: https://apt.releases.hashicorp.com/gpg
        debrepo_gpg_key_path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        debrepo_string: >-
          deb [arch={{ debrepo_dpkg_arch.stdout }} signed-by={{ debrepo_gpg_key_path }}]
          https://apt.releases.hashicorp.com {{ debrepo_distro_codename.stdout }} main
      when: ansible_facts['os_family'] == "Debian"

    - name: Add repository (RedHat)
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/{{ vagrant_redhat_repo }}/hashicorp.repo
        dest: /etc/yum.repos.d/vagrant.repo
        mode: "0644"
      vars:
        vagrant_redhat_repo: "{% if ansible_facts['distribution'] == \"Fedora\" %}fedora{% else %}RHEL{% endif %}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Vagrant (Debian)
      ansible.builtin.apt:
        name: vagrant
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Vagrant (RedHat)
      ansible.builtin.dnf:
        name: vagrant
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: Validate install
      ansible.builtin.command:
        cmd: vagrant --version
      changed_when: false
