---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: playbooks-deb11
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-deb12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-deb13
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-ub22
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-ub24
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-rl9
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: playbooks-rl10
    image: "geerlingguy/docker-rockylinux10-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      # Avoids "sudo" problem in rl9
      remote_user: root
  playbooks:
    converge: ../../${MOLECULE_PLAYBOOK:-molecule/default/converge.yml}
