---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: playbooks
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      # Avoids "sudo" problem in rl9
      remote_user: root
  playbooks:
    converge: ../../${MOLECULE_PLAYBOOK:-molecule/default/converge.yml}
